<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Car;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cars = [
            [
                'make' => 'Jeep',
                'model' => 'Renegade',
                'year' => 2023,
                'type' => 'suv',
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 4,
                'luggage_capacity' => '2 bags',
                'daily_rate' => 265.00,
                'weekly_rate' => 1590.00,
                'monthly_rate' => 6360.00,
                'image' => 'jeep-renegade.jpg',
                'features' => ['GPS Navigation', 'Bluetooth', 'Air Conditioning', 'USB Charging'],
                'description' => 'Compact SUV perfect for city driving and weekend adventures.',
                'is_available' => true,
                'is_featured' => true,
                'likes_count' => 25,
                'average_rating' => 4.2,
                'total_bookings' => 45
            ],
            [
                'make' => 'BMW',
                'model' => 'M5',
                'year' => 2023,
                'type' => 'luxury',
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 4,
                'luggage_capacity' => '2 bags',
                'daily_rate' => 244.00,
                'weekly_rate' => 1464.00,
                'monthly_rate' => 5856.00,
                'image' => 'bmw-m5.jpg',
                'features' => ['Premium Sound System', 'Leather Seats', 'GPS Navigation', 'Climate Control'],
                'description' => 'High-performance luxury sedan with exceptional driving dynamics.',
                'is_available' => true,
                'is_featured' => true,
                'likes_count' => 79,
                'average_rating' => 4.8,
                'total_bookings' => 62
            ],
            [
                'make' => 'Ferrari',
                'model' => 'Enzo',
                'year' => 2023,
                'type' => 'exotic',
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'seats' => 2,
                'doors' => 2,
                'luggage_capacity' => '1 bag',
                'daily_rate' => 167.00,
                'weekly_rate' => 1002.00,
                'monthly_rate' => 4008.00,
                'image' => 'ferrari-enzo.jpg',
                'features' => ['Sport Suspension', 'Carbon Fiber Interior', 'Racing Seats', 'Premium Audio'],
                'description' => 'Iconic supercar delivering unmatched performance and style.',
                'is_available' => true,
                'is_featured' => true,
                'likes_count' => 55,
                'average_rating' => 4.9,
                'total_bookings' => 23
            ],
            [
                'make' => 'Ford',
                'model' => 'Raptor',
                'year' => 2023,
                'type' => 'truck',
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 4,
                'luggage_capacity' => '3 bags',
                'daily_rate' => 147.00,
                'weekly_rate' => 882.00,
                'monthly_rate' => 3528.00,
                'image' => 'ford-raptor.jpg',
                'features' => ['4WD', 'Off-Road Package', 'Tow Package', 'Bed Liner'],
                'description' => 'High-performance off-road truck built for adventure.',
                'is_available' => true,
                'is_featured' => false,
                'likes_count' => 89,
                'average_rating' => 4.5,
                'total_bookings' => 34
            ],
            [
                'make' => 'Mini',
                'model' => 'Cooper',
                'year' => 2023,
                'type' => 'compact',
                'fuel_type' => 'petrol',
                'transmission' => 'manual',
                'seats' => 4,
                'doors' => 2,
                'luggage_capacity' => '2 bags',
                'daily_rate' => 238.00,
                'weekly_rate' => 1428.00,
                'monthly_rate' => 5712.00,
                'image' => 'mini-cooper.jpg',
                'features' => ['Bluetooth', 'Air Conditioning', 'Premium Audio', 'Sport Seats'],
                'description' => 'Iconic compact car with distinctive style and agile handling.',
                'is_available' => true,
                'is_featured' => false,
                'likes_count' => 87,
                'average_rating' => 4.3,
                'total_bookings' => 67
            ],
            [
                'make' => 'Volkswagen',
                'model' => 'Polo',
                'year' => 2023,
                'type' => 'economy',
                'fuel_type' => 'petrol',
                'transmission' => 'manual',
                'seats' => 5,
                'doors' => 4,
                'luggage_capacity' => '2 bags',
                'daily_rate' => 106.00,
                'weekly_rate' => 636.00,
                'monthly_rate' => 2544.00,
                'image' => 'vw-polo.jpg',
                'features' => ['Air Conditioning', 'Radio', 'Power Steering', 'Electric Windows'],
                'description' => 'Reliable and economical hatchback perfect for city driving.',
                'is_available' => true,
                'is_featured' => false,
                'likes_count' => 37,
                'average_rating' => 4.1,
                'total_bookings' => 89
            ],
            [
                'make' => 'Chevrolet',
                'model' => 'Camaro',
                'year' => 2023,
                'type' => 'sports_car',
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'seats' => 4,
                'doors' => 2,
                'luggage_capacity' => '2 bags',
                'daily_rate' => 245.00,
                'weekly_rate' => 1470.00,
                'monthly_rate' => 5880.00,
                'image' => 'chevrolet-camaro.jpg',
                'features' => ['Sport Mode', 'Premium Audio', 'Leather Interior', 'Performance Tires'],
                'description' => 'American muscle car with modern performance and classic style.',
                'is_available' => true,
                'is_featured' => true,
                'likes_count' => 39,
                'average_rating' => 4.6,
                'total_bookings' => 28
            ],
            [
                'make' => 'Hyundai',
                'model' => 'Staria',
                'year' => 2023,
                'type' => 'minivan',
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'seats' => 8,
                'doors' => 4,
                'luggage_capacity' => '4 bags',
                'daily_rate' => 191.00,
                'weekly_rate' => 1146.00,
                'monthly_rate' => 4584.00,
                'image' => 'hyundai-staria.jpg',
                'features' => ['3 Rows Seating', 'Sliding Doors', 'Rear AC', 'Family Package'],
                'description' => 'Spacious minivan ideal for family trips and group travel.',
                'is_available' => true,
                'is_featured' => false,
                'likes_count' => 23,
                'average_rating' => 4.0,
                'total_bookings' => 41
            ],
            [
                'make' => 'Toyota',
                'model' => 'RAV4',
                'year' => 2023,
                'type' => 'suv',
                'fuel_type' => 'hybrid',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 4,
                'luggage_capacity' => '3 bags',
                'daily_rate' => 114.00,
                'weekly_rate' => 684.00,
                'monthly_rate' => 2736.00,
                'image' => 'toyota-rav.jpg',
                'features' => ['Hybrid Engine', 'AWD', 'Safety Package', 'Eco Mode'],
                'description' => 'Fuel-efficient SUV with excellent reliability and safety ratings.',
                'is_available' => true,
                'is_featured' => true,
                'likes_count' => 63,
                'average_rating' => 4.4,
                'total_bookings' => 76
            ],
            [
                'make' => 'Bentley',
                'model' => 'Continental',
                'year' => 2023,
                'type' => 'luxury',
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'seats' => 4,
                'doors' => 2,
                'luggage_capacity' => '2 bags',
                'daily_rate' => 299.00,
                'weekly_rate' => 1794.00,
                'monthly_rate' => 7176.00,
                'image' => 'bentley.jpg',
                'features' => ['Handcrafted Interior', 'Premium Sound', 'Massage Seats', 'Champagne Cooler'],
                'description' => 'Ultimate luxury grand tourer with unparalleled craftsmanship.',
                'is_available' => true,
                'is_featured' => true,
                'likes_count' => 45,
                'average_rating' => 4.9,
                'total_bookings' => 15
            ],
            [
                'make' => 'Lexus',
                'model' => 'ES',
                'year' => 2023,
                'type' => 'premium',
                'fuel_type' => 'hybrid',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 4,
                'luggage_capacity' => '3 bags',
                'daily_rate' => 131.00,
                'weekly_rate' => 786.00,
                'monthly_rate' => 3144.00,
                'image' => 'lexus.jpg',
                'features' => ['Hybrid Technology', 'Premium Interior', 'Advanced Safety', 'Quiet Cabin'],
                'description' => 'Premium sedan combining luxury comfort with fuel efficiency.',
                'is_available' => true,
                'is_featured' => false,
                'likes_count' => 61,
                'average_rating' => 4.5,
                'total_bookings' => 52
            ],
            [
                'make' => 'Land Rover',
                'model' => 'Range Rover',
                'year' => 2023,
                'type' => 'luxury',
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 4,
                'luggage_capacity' => '4 bags',
                'daily_rate' => 228.00,
                'weekly_rate' => 1368.00,
                'monthly_rate' => 5472.00,
                'image' => 'range-rover.jpg',
                'features' => ['Air Suspension', 'Terrain Response', 'Panoramic Roof', 'Premium Package'],
                'description' => 'Luxury SUV with exceptional off-road capability and refinement.',
                'is_available' => true,
                'is_featured' => true,
                'likes_count' => 69,
                'average_rating' => 4.7,
                'total_bookings' => 31
            ]
        ];

        foreach ($cars as $carData) {
            Car::create($carData);
        }
    }
}
